[languages]
nodejs.version = "18"

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install",
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "node server/index.js"

